/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseworkzakernychnaoop;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Johny
 */
public class EntityCreator extends javax.swing.JFrame {
    private MagicOrganisation org;
    private String entityName;
    private int magicLevel;
    private int magicPower;
    private int entityType;
    
    public EntityCreator() {
        initComponents();
        
        refreshCreator();
    }
    
    private void refreshCreator() {
        String organization = (String)jComboBoxMO.getSelectedItem();
        String magicLevel = (String)jComboBoxLevel.getSelectedItem();
        
        this.magicLevel = -1;
        
        switch(magicLevel) {
            case "Маг": this.magicLevel = MagicEntity.HEADER_MAG; break;
            case "Студент": this.magicLevel = MagicEntity.MAG; break;
            case "Істота": this.magicLevel = MagicEntity.MAGIC_ENTITY; break;
        }
        
        org = null;
        
        switch(organization) {
            case "Нейтральний": 
                entityType = MagicEntity.NEUTRAL_PERSON;
                org = MainWindow.neutrals; 
                break;
            case "Орден Фенікса": 
                entityType = MagicEntity.THE_ORDER_MEMBER;
            org = MainWindow.orden; 
                break;
            case "Смертежери": 
                entityType = MagicEntity.THE_DEATH_EATER;
                org = MainWindow.eaters; 
                break;
        }
        
        if(org != null) setComboBoxNamesItems(org.getNamesList(this.magicLevel));
                
        jSliderPower.setMinimum((this.magicLevel - 1) * 20);
        jSliderPower.setMaximum(this.magicLevel * 20);
    }
    
    private void setComboBoxNamesItems(String[] itemList) {
        if(itemList != null){
            jComboBoxName.setModel(new DefaultComboBoxModel(itemList));
        }
        //jComboBoxName.removeItemAt(itemList.length - 1);
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMO = new javax.swing.JComboBox();
        jComboBoxName = new javax.swing.JComboBox();
        jComboBoxLevel = new javax.swing.JComboBox();
        jSliderPower = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Створення істоти");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Магічна організація: ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Магічний рівень: ");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Персонаж: ");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Магічна сила: ");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxMO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxMO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Нейтральний", "Орден Фенікса", "Смертежери" }));
        jComboBoxMO.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMOItemStateChanged(evt);
            }
        });

        jComboBoxName.setEditable(true);
        jComboBoxName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBoxLevel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Маг", "Студент", "Істота" }));
        jComboBoxLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxLevelItemStateChanged(evt);
            }
        });
        jComboBoxLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLevelActionPerformed(evt);
            }
        });

        jButton1.setText("Створити");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxMO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSliderPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSliderPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLevelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        entityName = (String) jComboBoxName.getSelectedItem();
        magicPower = jSliderPower.getValue();
        
        org.addEntity(MagicEntity.getEntity(entityName, magicPower, magicLevel, entityType));
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxMOItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMOItemStateChanged
        refreshCreator();
    }//GEN-LAST:event_jComboBoxMOItemStateChanged

    private void jComboBoxLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxLevelItemStateChanged
        refreshCreator();
    }//GEN-LAST:event_jComboBoxLevelItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxLevel;
    private javax.swing.JComboBox jComboBoxMO;
    private javax.swing.JComboBox jComboBoxName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSlider jSliderPower;
    // End of variables declaration//GEN-END:variables
}
